engines:
  eslint:
    enabled: true
    channel: "eslint-4"
  pep8:
    enabled: true
  pylint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 100
          python_version: 3
exclude_patterns:
- "**/migrations/"
- "tests/"
- "**/test_*"
ratings:
  paths:
  - saleor/**
